---
- name: install packages
  with_items: "{{ rspamd_packages }}"
  pkgng:
    name: "{{ item.name }}"
  notify:
    - restart rspamd

- name: configure rspamd service
  template:
    src: rspamd.j2
    dest: /etc/rc.conf.d/rspamd
    owner: root
    group: wheel
  notify:
    - restart rspamd

- name: create local.d
  file:
    path: /usr/local/etc/rspamd/local.d
    state: directory

- name: get hoster name
  shell: "hostname -d | cut -f 1 -d ."
  register: hoster

- name: configure dkim signing
  template:
    src: dkim_signing.conf.j2
    dest: /usr/local/etc/rspamd/local.d/dkim_signing.conf
  notify:
    - restart rspamd

- name: configure milter
  template:
    src: milter_headers.conf.j2
    dest: /usr/local/etc/rspamd/local.d/milter_headers.conf
  notify:
    - restart rspamd

- name: create dkim directory
  file:
    path: /var/db/rspamd/dkim
    state: directory

- name: generate dkim key
  shell: "rspamadm dkim_keygen -s {{ hoster.stdout }} -k /var/db/rspamd/dkim/{{ hoster.stdout }}.{{ mail_domain }}.key -d {{ mail_domain }} >/var/db/rspamd/dkim/{{ hoster.stdout }}.{{ mail_domain }}.public"
  args:
    creates: "/var/db/rspamd/dkim/{{ mail_domain }}.{{ hoster.stdout }}.key"
  notify:
    - restart rspamd
